-- Add new fields to profiles table for settings
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS push_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS tournament_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS match_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS team_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS friend_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS message_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS marketing_notifications BOOLEAN DEFAULT FALSE;

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS theme_preference VARCHAR(20) DEFAULT 'system';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS accent_color VARCHAR(20) DEFAULT 'blue';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS font_size VARCHAR(20) DEFAULT 'medium';

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS profile_visibility VARCHAR(20) DEFAULT 'public';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS show_online_status BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS show_activity BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS allow_friend_requests BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS allow_team_invites BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS allow_direct_messages VARCHAR(20) DEFAULT 'everyone';

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS discord_username VARCHAR(100);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS twitter_url VARCHAR(255);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS twitch_url VARCHAR(255);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS youtube_url VARCHAR(255);
